version: '3'
services:
  kk:
    build:
      context: .
    container_name: keycloakmin
    volumes:
      - /tmp/keycloak/standalone/data:/keycloak/standalone/data
    ports:
      - 8443:8443
